### ISSUE TITLE
Instructions and requirements unclear for PAK Viewer

### ISSUE THREAD

**Issue by hemebond** [gongpha/gdQmapbsp#38]
When running `hub.tscn` to view maps, it's unclear what it actually needs and I can not get it to load any map to view.

![image](https://github.com/user-attachments/assets/82c56c7c-6bba-4ce6-a371-b3728c75e8e6)

Is it only usable for maps (.bsp) in a PAK file? What should "MAP Directory" point to?

**Comment by gongpha** [comment]
The BSP files need to be loaded together with MAP to generate collisions (due to the BSP compilation process, the original brush shapes are discarded). The MAP Directory should point to the directory with MAP files contained.

For example, if `/home/me/maps` is entered, the directory should have map files matched to the BSP file names regardless of the subdirectory :
```
/home/me/maps/start.map
/home/me/maps/e1m1.map
/home/me/maps/e1m2.map
/home/me/maps/e1m3.map
/home/me/maps/e1m4.map
. . .
```

I'm unsure if there is any MAP file indexing issue on Linux. I haven't tested it yet

**Comment by hemebond** [comment]
The `quake-remap/id1/maps/src/` directory that I entered has the .map files for all id1 maps. I'll have a look at the code later and see if there's a Linux-specific issue there.

**Comment by gongpha** [comment]
Looks nice ! May you make a PR for this ?
